declare namespace Express {
  interface Request {
    body: any;
    coldStorage?: {
      enabled: boolean;
      type: string;
      path?: string;
      ledgerSeq: number;
    };
    network: import('../profiles').NetworkName;
    networkProfile: import('../profiles').NetworkProfile;
    /** Unique ID for this HTTP request (correlation). */
    requestId: string;
    /** OpenTelemetry / B3 trace ID propagated from upstream or generated by OTel. */
    traceId: string;
    /** OpenTelemetry / B3 span ID of the root server span. */
    spanId: string;
    /** Authenticated user populated by requireAuth middleware. */
    user?: {
      id: string;
      address: string;
      role: import('../auth/rbac').Role;
      tier: import('../auth/rbac').Tier;
      sessionId: string;
      appId: string;
    };
  }
}
